sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=myrobot
    # REGISTRY_PASS=...
    - secret: "<something long>"

script:
  - docker build --tag raniot/gettingstarted ./gettingstarted
  - docker run raniot/gettingstarted

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push raniot/gettingstarted
  on:
    branch: master
